# Generated by Django 5.1.7 on 2025-07-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('operacional', 'Operacional'), ('executivo', 'Executivo')], max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('preenchimento', 'Em Preenchimento'), ('pendente', 'Pendente Aprovação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='rascunho', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
