# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='formulario_respondido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='form.formulariorespondido'),
        ),
        migrations.AddField(
            model_name='report',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('formulario_respondido', 'tipo')},
        ),
    ]
