name: future
version: "3.8"

networks:
  future_network:
    driver: bridge

services:
  frontend:
    container_name: future_frontend
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always
    networks:
      - future_network

  backend:
    container_name: future_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - ENV=development
      - CHOKIDAR_USEPOLLING=true
      - POSTGRES_DB=cybersec_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fs3m2025
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    restart: always
    networks:
      - future_network

  db:
    image: postgres:latest
    container_name: future_db
    restart: always
    environment:
      POSTGRES_DB: cybersec_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fs3m2025
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - future_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cybersec_db" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:
    driver: local
