version: "3.8"

networks:
  future_network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: future_db
    restart: always
    environment:
      POSTGRES_DB: cybersec_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fs3m2025
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - pg_wal_archive:/var/lib/postgresql/wal_archive
    networks:
      - future_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cybersec_db" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:
  pg_wal_archive:
