# Generated by Django 5.1.7 on 2025-07-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Governar (GV)', 'Governar (GV)'), ('Identificar (ID)', 'Identificar (ID)'), ('Proteger (PR)', 'Proteger (PR)'), ('Detectar (DE)', 'Detectar (DE)'), ('Responder (RS)', 'Responder (RS)'), ('Recuperar (RC)', 'Recuperar (RC)')], max_length=50)),
                ('aplicabilidade', models.CharField(choices=[('Política', 'Política'), ('Prática', 'Prática'), ('Ambas', 'Ambas')], default='Ambas', help_text='Indica se a recomendação se aplica a Política, Prática ou Ambas.', max_length=20)),
                ('tecnologia', models.CharField(default='Agnóstico', max_length=255)),
                ('nist', models.CharField(max_length=50)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=50)),
                ('responsavel', models.CharField(default='Não definido', max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('meses', models.PositiveIntegerField()),
                ('detalhes', models.TextField()),
                ('investimentos', models.CharField(max_length=255)),
                ('riscos', models.TextField(default='Não informado')),
                ('justificativa', models.TextField(default='Não informado')),
                ('observacoes', models.TextField(default='Nenhuma observação adicional')),
                ('urgencia', models.CharField(choices=[('1', 'Muito Baixo'), ('2', 'Baixo'), ('3', 'Moderado'), ('4', 'Alto'), ('5', 'Muito Alto')], max_length=1)),
                ('gravidade', models.CharField(choices=[('1', 'Muito Baixa'), ('2', 'Baixa'), ('3', 'Moderada'), ('4', 'Alta'), ('5', 'Muito Alta')], max_length=1)),
                ('cumprida', models.BooleanField(default=False)),
                ('data_cumprimento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perguntaId', models.CharField(blank=True, db_column='perguntaId', default='Não informado', max_length=50, verbose_name='ID da Pergunta')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-prioridade', 'data_fim'],
            },
        ),
    ]
