# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_initial'),
        ('recomendacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='analista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacoes_analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='formulario_respondido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_formulario', to='form.formulariorespondido'),
        ),
    ]
