# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(default='Nenhuma observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('prazo', models.CharField(blank=True, default='', max_length=255)),
                ('gravidade', models.CharField(blank=True, default='', max_length=255)),
                ('urgencia', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(blank=True, default='', max_length=255)),
                ('orcamentoMax', models.CharField(blank=True, default='', max_length=255)),
                ('formularioRespondidoId', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeAcaoRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('A Fazer', 'A Fazer'), ('Em Progresso', 'Em Progresso'), ('Finalizado', 'Finalizado')], default='A Fazer', max_length=20)),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
