# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planodeacao', '0001_initial'),
        ('recomendacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planodeacaorecomendacao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planodeacao.planodeacao'),
        ),
        migrations.AddField(
            model_name='planodeacaorecomendacao',
            name='recomendacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacoes.recomendacao'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='recomendacoes',
            field=models.ManyToManyField(through='planodeacao.PlanoDeAcaoRecomendacao', to='recomendacoes.recomendacao'),
        ),
    ]
