# Generated by Django 5.1.7 on 2025-07-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Repetido'), (3, 'Definido'), (4, 'Gerenciado'), (5, 'Otimizado')])),
                ('pratica', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Repetido'), (3, 'Definido'), (4, 'Gerenciado'), (5, 'Otimizado')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'Em progresso'), ('completed', 'Concluído'), ('pending', 'Pendente')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('security', 'Segurança'), ('privacy', 'Privacidade'), ('compliance', 'Compliance')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('policy_maturity', models.IntegerField(blank=True, choices=[(1, 'Inicial'), (2, 'Gerenciado'), (3, 'Definido'), (4, 'Repetido'), (5, 'Otimizado')], null=True)),
                ('practice_maturity', models.IntegerField(blank=True, choices=[(1, 'Inicial'), (2, 'Gerenciado'), (3, 'Definido'), (4, 'Repetido'), (5, 'Otimizado')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('GV', 'Govern'), ('ID', 'Identity'), ('PR', 'Protect'), ('DE', 'Detect'), ('RS', 'Response'), ('RC', 'Recovery')], max_length=1000)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=500)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('score', models.IntegerField()),
                ('category', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], max_length=100)),
                ('assessment_date', models.DateField()),
            ],
        ),
    ]
