# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariorespondido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_respondidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulariorespondido',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_respondidos', to='form.formulario'),
        ),
        migrations.AddField(
            model_name='formulariorespondido',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_designados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='form.categoria'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='formulario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='form.formulario'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='formulario_respondido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='form.formulariorespondido'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pergunta'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formulariorespondido',
            unique_together={('cliente', 'formulario', 'versao')},
        ),
        migrations.AlterUniqueTogether(
            name='resposta',
            unique_together={('formulario_respondido', 'pergunta')},
        ),
    ]
