# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('formulario_respondido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maturity_assessment', to='form.formulariorespondido')),
            ],
            options={
                'verbose_name': 'Avaliação de Maturidade',
                'verbose_name_plural': 'Avaliações de Maturidade',
            },
        ),
        migrations.CreateModel(
            name='CategoriaMaturity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('media_politica', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('media_pratica', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('media_total', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('objetivo', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('status', models.CharField(default='Não Avaliado', max_length=20)),
                ('tipo', models.CharField(choices=[('FUNCAO', 'Função'), ('CATEGORIA', 'Categoria')], default='CATEGORIA', max_length=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.categoria')),
                ('maturity_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_maturity', to='maturity_assessment.maturityassessment')),
            ],
            options={
                'ordering': ['tipo', 'sigla'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaMaturity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pratica', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('objetivo', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('SUBCATEGORIA', 'Subcategoria'), ('PERGUNTA', 'Pergunta')], default='PERGUNTA', max_length=12)),
                ('categoria_maturity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_maturity', to='maturity_assessment.categoriamaturity')),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.pergunta')),
            ],
        ),
    ]
