# Generated by Django 5.1.7 on 2025-07-29 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.', max_length=150, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este email.'}, max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('subcliente', 'Subcliente'), ('funcionario', 'Funcionário'), ('gestor', 'Gestor')], default='cliente', max_length=50, verbose_name='Tipo de Usuário')),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'role': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclientes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Associado')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos aos quais este usuário pertence.', related_name='customuser_groups', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='customuser_permissions', to='auth.permission', verbose_name='Permissões do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
                'permissions': [('view_user', 'Pode ver usuários'), ('change_user', 'Pode alterar usuários'), ('delete_user', 'Pode excluir usuários'), ('view_report', 'Pode ver relatórios de segurança'), ('create_report', 'Pode criar relatórios de segurança'), ('delete_report', 'Pode excluir relatórios de segurança')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
    ]
