name: Build and deploy to Azure Web App

on:
  push:
    branches: [ azure-cloud ]  # Altere para sua branch principal se necessário
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: future
  AZURE_WEBAPP_PLAN_NAME: ASP-fs3m-9075
  RESOURCE_GROUP: fs3m

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container images
        run: |
          docker-compose -f docker-compose.prod.yml build
          # Aqui você pode adicionar comandos para push para um registry se necessário
        env:
          DOCKER_BUILDKIT: 1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: 'index.docker.io/nginx'  # Substitua pela sua imagem principal
          configuration-file: 'docker-compose.prod.yml'  # Especifique seu arquivo compose de produção
          # Se estiver usando um registry privado, adicione:
          # registry-username: ${{ secrets.REGISTRY_USERNAME }}
          # registry-password: ${{ secrets.REGISTRY_PASSWORD }}
