name: CD to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to GCP VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.GCP_VM_USER }}"

      - name: Deploy via SSH (derruba backend e sobe tudo)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/${{ secrets.GCP_VM_USER }}

            echo "🔍 Verificando versão do Docker Compose..."
            docker compose version || docker-compose version

            echo "⏬ Parando o backend primeiro..."
            docker compose -f docker-compose.prod.yml stop backend || docker-compose -f docker-compose.prod.yml stop backend
            docker compose -f docker-compose.prod.yml rm -f backend || docker-compose -f docker-compose.prod.yml rm -f backend

            echo "⬆️ Subindo tudo novamente com build..."
            docker compose -f docker-compose.prod.yml pull || docker-compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --build --remove-orphans || docker-compose -f docker-compose.prod.yml up -d --build --remove-orphans

            echo "✅ Deploy concluído com sucesso!"
